Repository upstage-org/upstage, pull requests merged in 2020-11, with the labels that each got.

#68 Static Asset System
  .gitignore
  assets/__init__.py
  assets/data.py
  assets/sqlfiles/create.sql
  assets/system.py
  assets/views/__init__.py
  assets/views/assets.py
  assets/views/licenses.py
Labels: media management, orchestration

#66 Basic Stage
  ui/lib/anime.js
  ui/lib/anime.min.js
  ui/static/css/reset.css
  ui/static/css/stage.css
  ui/static/stage.html
  ui/static/upstage.png
Labels: stage

#73 initial vue code, basic stage
  .gitignore
  ui/dashboard/README.md
  ui/dashboard/babel.config.js
  ui/dashboard/jsconfig.json
  ui/dashboard/package.json
  ui/dashboard/public/_redirects
  ui/dashboard/public/favicon.ico
  ui/dashboard/public/index.html
  ui/dashboard/src/App.vue
  ui/dashboard/src/assets/defaultava.png
  ui/dashboard/src/assets/logo.png
  ui/dashboard/src/assets/logo.svg
  ui/dashboard/src/assets/upstage.png
  ui/dashboard/src/components/AppNav.vue
  ui/dashboard/src/main.js
  ui/dashboard/src/plugins/vuetify.js
  ui/dashboard/src/router/index.js
  ui/dashboard/src/services/auth.js
  ui/dashboard/src/services/base.js
  ui/dashboard/src/services/baseService.js
  ui/dashboard/src/services/index.js
  ui/dashboard/src/services/user.js
  ui/dashboard/src/store/modules/auth.js
  ui/dashboard/src/store/modules/user.js
  ui/dashboard/src/store/store.js
  ui/dashboard/src/utils/auth.js
  ui/dashboard/src/utils/constants.js
  ui/dashboard/src/views/About.vue
  ui/dashboard/src/views/Dashboard.vue
  ui/dashboard/src/views/Home.vue
  ui/dashboard/src/views/Login.vue
  ui/dashboard/vue.config.js
  ui/dashboard/yarn.lock
Labels: good first issue

#74 Basic Orchestration
  dispatcher/__init__.py
  run_upstage.py
  ui/__init__.py
Labels: orchestration

#75 Issue 70 group cleanup
  group/__init__.py
  group/roles.py
  group/schema.py
  group/totp.py
  group/user_api.py
  group/user_utils.py
  requirements.pip
Labels: access control

#77 Issue 76 infra microservices
  .gitignore
  asset/__init__.py
  asset/models.py
  asset/system.py
  asset/unittests/crud_tests.py
  asset/views/__init__.py
  asset/views/assets.py
  asset/views/licenses.py
  auth/__init__.py
  auth/models.py
  config/project_globals.py
  dispatcher/__init__.py
  dispatcher/__main__.py
  group/__init__.py
  ui/__init__.py
  user/__init__.py
  user/models.py
Labels: access control, orchestration
