Repository upstage-org/upstage, pull requests merged in 2020-12, with the labels that each got.

#87 Application Protocol
  ui/protocol-spike/200px-Snoopy_Peanuts.png
  ui/protocol-spike/actions.js
  ui/protocol-spike/anime.min.js
  ui/protocol-spike/events.js
  ui/protocol-spike/index.html
  ui/protocol-spike/init.js
  ui/protocol-spike/mqttws31.min.js
  ui/protocol-spike/protocol.js
  ui/protocol-spike/style.css
  ui/protocol-spike/utils.js
Labels: protocol, spike

#94 fixing bugs caused by restructure
  asset/models.py
  asset/system.py
  asset/views/assets.py
  license/models.py
  license/views/assets.py
  license/views/licenses.py
  run_upstage.py
  ui/dashboard/yarn.lock
Labels: media management, orchestration

#99 Issue 98 upgrade vue 3
  ui/dashboard/.browserslistrc
  ui/dashboard/.eslintrc.js
  ui/dashboard/.gitignore
  ui/dashboard/README.md
  ui/dashboard/jsconfig.json
  ui/dashboard/package.json
  ui/dashboard/public/index.html
  ui/dashboard/src/App.vue
  ui/dashboard/src/assets/logo.svg
  ui/dashboard/src/components/AppNav.vue
  ui/dashboard/src/components/Footer.vue
  ui/dashboard/src/components/NavBar.vue
  ui/dashboard/src/main.js
  ui/dashboard/src/plugins/vuetify.js
  ui/dashboard/src/router/index.js
  ui/dashboard/src/services/baseService.js
  ui/dashboard/src/store/index.js
  ui/dashboard/src/styles/bulma.scss
  ui/dashboard/src/views/About.vue
  ui/dashboard/src/views/Dashboard.vue
  ui/dashboard/src/views/Home.vue
  ui/dashboard/src/views/LegacyDashboard.vue
  ui/dashboard/src/views/Login.vue
  ui/dashboard/src/views/Stage.vue
  ui/dashboard/vue.config.js
  ui/dashboard/yarn.lock
Labels: spike
