Repository upstage-org/upstage, pull requests merged in 2021-04, with the labels that each got.

#215 Issue 206 My Stages
  ui/dashboard/src/components/DataTable/index.vue
  ui/dashboard/src/components/form/Switch.vue
  ui/dashboard/src/components/stage/StageTable.vue
  ui/dashboard/src/router/index.js
  ui/dashboard/src/services/graphql/composable.js
  ui/dashboard/src/utils/auth.js
  ui/dashboard/src/utils/common.js
  ui/dashboard/src/views/dashboard/Dashboard.vue
  ui/dashboard/src/views/dashboard/Layout.vue
  ui/dashboard/src/views/dashboard/Media/index.vue
Labels: enhancement

#232 UI/UX Enhancement
  ui/dashboard/public/icons/maximize.svg
  ui/dashboard/public/icons/pause.svg
  ui/dashboard/public/icons/scene.svg
  ui/dashboard/public/icons/stage.svg
  ui/dashboard/src/components/MediaUpload.vue
  ui/dashboard/src/components/form/Upload.vue
  ui/dashboard/src/components/stage/Chat/index.vue
  ui/dashboard/src/components/stage/Toolbox/index.vue
  ui/dashboard/src/components/stage/Toolbox/tools/Audio.vue
Labels: media management, workshop

#239 Initial docs
  .gitignore
  docs/Makefile
  docs/change_password.png
  docs/change_profile.png
  docs/conf.py
  docs/dashboard.png
  docs/developer_manual.rst
  docs/glossary.rst
  docs/index.rst
  docs/installation_manual.rst
  docs/login_box.png
  docs/logo.svg
  docs/make.bat
  docs/register_box.png
  docs/stage_details.png
  docs/user_manual.rst
Labels: documentation

#250 Issue 150 Slider Mode
  ui/dashboard/src/components/objects/Avatar/ContextMenu.vue
  ui/dashboard/src/components/objects/Avatar/index.vue
  ui/dashboard/src/components/objects/Object.vue
  ui/dashboard/src/components/objects/OpacitySlider.vue
  ui/dashboard/src/components/objects/Text.vue
  ui/dashboard/src/store/modules/stage/index.js
Labels: bug

#263 Fix Nested Modal Size
  ui/dashboard/src/components/Modal.vue
Labels: bug

#269 Update user_manual.rst
  docs/user_manual.rst
Labels: documentation

#280 Update user_manual.rst
  docs/user_manual.rst
Labels: backstage

#282 dashboard into backstage
  docs/user_manual.rst
Labels: documentation
