Repository upstage-org/upstage, pull requests merged in 2021-05, with the labels that each got.

#304 Change Target Branch for App1
  .github/workflows/app1.yml
Labels: pipeline

#306 Issue 258 Enter stage (cont)
  ui/dashboard/src/store/modules/stage/index.js
  ui/dashboard/src/views/dashboard/StageManagement/Records.vue
  ui/dashboard/src/views/live/LoginPrompt.vue
Labels: access control

#312 Issue 57 Avatar Voice
  ui/dashboard/public/index.html
  ui/dashboard/public/js/mespeak/mespeak-core.js
  ui/dashboard/public/js/mespeak/mespeak.js
  ui/dashboard/public/js/mespeak/voices/ca.json
  ui/dashboard/public/js/mespeak/voices/cs.json
  ui/dashboard/public/js/mespeak/voices/de.json
  ui/dashboard/public/js/mespeak/voices/el.json
  ui/dashboard/public/js/mespeak/voices/en/en-n.json
  ui/dashboard/public/js/mespeak/voices/en/en-rp.json
  ui/dashboard/public/js/mespeak/voices/en/en-sc.json
  ui/dashboard/public/js/mespeak/voices/en/en-us.json
  ui/dashboard/public/js/mespeak/voices/en/en-wm.json
  ui/dashboard/public/js/mespeak/voices/en/en.json
  ui/dashboard/public/js/mespeak/voices/eo.json
  ui/dashboard/public/js/mespeak/voices/es-la.json
  ui/dashboard/public/js/mespeak/voices/es.json
  ui/dashboard/public/js/mespeak/voices/fi.json
  ui/dashboard/public/js/mespeak/voices/fr.json
  ui/dashboard/public/js/mespeak/voices/hu.json
  ui/dashboard/public/js/mespeak/voices/it.json
  ui/dashboard/public/js/mespeak/voices/kn.json
  ui/dashboard/public/js/mespeak/voices/la.json
  ui/dashboard/public/js/mespeak/voices/lv.json
  ui/dashboard/public/js/mespeak/voices/nl.json
  ui/dashboard/public/js/mespeak/voices/pl.json
  ui/dashboard/public/js/mespeak/voices/pt-pt.json
  ui/dashboard/public/js/mespeak/voices/pt.json
  ui/dashboard/public/js/mespeak/voices/ro.json
  ui/dashboard/public/js/mespeak/voices/sk.json
  ui/dashboard/public/js/mespeak/voices/sv.json
  ui/dashboard/public/js/mespeak/voices/tr.json
  ui/dashboard/public/js/mespeak/voices/zh-yue.json
  ui/dashboard/public/js/mespeak/voices/zh.json
  ui/dashboard/src/components/form/Dropdown.vue
  ui/dashboard/src/components/stage/SettingPopup/settings/VoiceParameters.vue
  ui/dashboard/src/services/speech/index.js
  ui/dashboard/src/services/speech/voice.js
  ui/dashboard/src/store/modules/stage/index.js
Labels: audio

#313 Issue 274 Backstage
  ui/dashboard/src/components/Breadcrumb.vue
  ui/dashboard/src/components/NavBar.vue
  ui/dashboard/src/components/stage/ActionButtons.vue
  ui/dashboard/src/components/stage/StageTable.vue
  ui/dashboard/src/router/index.js
  ui/dashboard/src/views/Login.vue
  ui/dashboard/src/views/backstage/Admin/DeleteUser.vue
  ui/dashboard/src/views/backstage/Admin/ProfileManagement.vue
  ui/dashboard/src/views/backstage/Admin/RegistrationApproval.vue
  ui/dashboard/src/views/backstage/Admin/ResetPassword.vue
  ui/dashboard/src/views/backstage/Admin/SwitchRole.vue
  ui/dashboard/src/views/backstage/Admin/SystemConfigurations.vue
  ui/dashboard/src/views/backstage/Admin/UploadLimit.vue
  ui/dashboard/src/views/backstage/Admin/UserTable.vue
  ui/dashboard/src/views/backstage/Admin/index.vue
  ui/dashboard/src/views/backstage/Layout.vue
  ui/dashboard/src/views/backstage/Media/EditMedia.vue
  ui/dashboard/src/views/backstage/Media/MediaList.vue
  ui/dashboard/src/views/backstage/Media/index.vue
  ui/dashboard/src/views/backstage/MyStages.vue
  ui/dashboard/src/views/backstage/Profile/ChangePassword.vue
  ui/dashboard/src/views/backstage/Profile/Information.vue
  ui/dashboard/src/views/backstage/Profile/index.vue
  ui/dashboard/src/views/backstage/StageManagement/Chat.vue
  ui/dashboard/src/views/backstage/StageManagement/General.vue
  ui/dashboard/src/views/backstage/StageManagement/Layout.vue
  ui/dashboard/src/views/backstage/StageManagement/Media.vue
  ui/dashboard/src/views/backstage/StageManagement/Records.vue
  ui/dashboard/src/views/backstage/StageManagement/Scenes.vue
  ui/dashboard/src/views/backstage/StageManagement/SweepStage.vue
  ui/dashboard/src/views/backstage/StageManagement/index.vue
  ui/dashboard/src/views/backstage/Stages.vue
  ui/dashboard/src/views/backstage/Workshop.vue
Labels: backstage

#315 add register box update img
  docs/register_box2.png
Labels: documentation

#316 delete old register dialog
  docs/register_box.png
Labels: documentation

#317 delete old login box
  docs/login_box.png
Labels: documentation

#318 add new login box
  docs/login-01.png
Labels: documentation

#319 old dashboard
  docs/dashboard.png
Labels: documentation

#320 new img backstage
  docs/backstage-list.png
Labels: documentation

#321 delete change profile img
  docs/change_profile.png
Labels: documentation

#322 add new image backstage profile
  docs/change-profile02.png
Labels: documentation

#323 add new image creating new stage
  docs/backstage-stage-creation.png
Labels: documentation

#324 update usermanual rst
  docs/user_manual.rst
Labels: documentation

#332 Issue 57 Artificial Click
  ui/dashboard/src/components/objects/Moveable.vue
  ui/dashboard/src/components/objects/Topping.vue
  ui/dashboard/src/store/modules/stage/index.js
  ui/dashboard/src/views/live/Layout.vue
  ui/dashboard/src/views/live/Preloader.vue
Labels: stage

#358 Issue 341 Speech Bubble
  ui/dashboard/src/components/objects/Topping.vue
  ui/dashboard/src/store/modules/stage/index.js
  ui/dashboard/src/views/live/Layout.vue
  ui/dashboard/src/views/live/Preloader.vue
Labels: avatars, stage

#364 R5-2021
  config/settings/__init__.py
  config/settings/your_hostname.py
  event_archive/__main__.py
  event_archive/actions.py
  event_archive/config.py
  event_archive/db.py
  event_archive/mqtt.py
  event_archive/system.py
  run_event_archive.py
  ui/dashboard/src/config.js
Labels: release

#365 new config across all machines
  system/dev/dev_app1_nginx_upstage.conf
  system/dev/mosquitto.conf
  system/dev/mosquitto_config.mk
  system/dev/mosquitto_logrotate_d
  system/prod/app1_nginx_upstage.conf
  system/prod/app1_ufw_commands.sh
  system/prod/event_archive.service
  system/prod/mongod.conf
  system/prod/mosquitto_confd_local_mosquitto.conf
  system/prod/mosquitto_root_cron.crontab
  system/prod/placeholder.ini
  system/prod/postgresql.conf
  system/prod/postgresql_pg_hba.conf
  system/prod/svc1_ufw_commands.sh
  system/prod/upstage.ini
  system/prod/upstage.service
Labels: config

#366 R6-2021
  system/dev/dev_app1_nginx_upstage.conf
  system/dev/mosquitto.conf
  system/dev/mosquitto_config.mk
  system/dev/mosquitto_logrotate_d
  system/prod/app1_nginx_upstage.conf
  system/prod/app1_ufw_commands.sh
  system/prod/event_archive.service
  system/prod/mongod.conf
  system/prod/mosquitto_confd_local_mosquitto.conf
  system/prod/mosquitto_root_cron.crontab
  system/prod/placeholder.ini
  system/prod/postgresql.conf
  system/prod/postgresql_pg_hba.conf
  system/prod/svc1_ufw_commands.sh
  system/prod/upstage.ini
  system/prod/upstage.service
Labels: release

#371 Isuse 4 Webcam Streaming
  ui/dashboard/src/components/objects/Streamer/PeerWebcam.vue
  ui/dashboard/src/components/objects/Streamer/index.vue
  ui/dashboard/src/components/stage/Toolbox/TopBar.vue
  ui/dashboard/src/components/stage/Toolbox/tools/Stream/Webcam.vue
  ui/dashboard/src/components/stage/Toolbox/tools/Stream/index.vue
  ui/dashboard/src/config.js
  ui/dashboard/src/store/modules/stage/reusable.js
  ui/dashboard/src/utils/constants.js
Labels: streaming

#373 Issue 4 Streaming
  config/schema.py
  stage/asset.py
  ui/dashboard/package.json
  ui/dashboard/public/icons/obs-logo.png
  ui/dashboard/src/assets/obs-instruction/1.png
  ui/dashboard/src/assets/obs-instruction/2.png
  ui/dashboard/src/assets/obs-instruction/3.png
  ui/dashboard/src/components/HLSPlayer.vue
  ui/dashboard/src/components/Image.vue
  ui/dashboard/src/components/RTMPStream.vue
  ui/dashboard/src/components/objects/Streamer/index.vue
  ui/dashboard/src/components/stage/Toolbox/tools/Stream/index.vue
  ui/dashboard/src/config.js
  ui/dashboard/src/services/graphql/stage.js
  ui/dashboard/src/store/modules/stage/index.js
  ui/dashboard/src/utils/rtmp.js
  ui/dashboard/src/views/backstage/Media/MediaForm.vue
  ui/dashboard/src/views/backstage/Media/MediaUpload.vue
  ui/dashboard/src/views/backstage/Media/OBSInstruction.vue
  ui/dashboard/src/views/live/Preloader.vue
  ui/dashboard/yarn.lock
Labels: streaming

#386 Issue 385 Nickname
  ui/dashboard/src/components/objects/OpacitySlider.vue
  ui/dashboard/src/store/modules/user.js
Labels: avatars
