Repository upstage-org/upstage, pull requests merged in 2021-06, with the labels that each got.

#393 Issue 352 Re-positioning things in depth
  ui/dashboard/src/components/objects/Avatar/ContextMenu.vue
  ui/dashboard/src/components/objects/Topping.vue
  ui/dashboard/src/views/backstage/Media/MediaList.vue
  ui/dashboard/src/views/live/ConnectionStatus.vue
Labels: stage

#395 Issue 2 Batch User Creation
  auth/auth_api.py
  stage/schema.py
  ui/dashboard/src/router/index.js
  ui/dashboard/src/services/graphql/user.js
  ui/dashboard/src/store/modules/cache.js
  ui/dashboard/src/store/modules/user.js
  ui/dashboard/src/utils/constants.js
  ui/dashboard/src/views/backstage/Admin/BatchUserCreation.vue
  ui/dashboard/src/views/backstage/Admin/index.vue
  ui/dashboard/src/views/backstage/Media/index.vue
  ui/dashboard/src/views/backstage/MyStages.vue
  ui/dashboard/src/views/backstage/Stages.vue
  user/models.py
  user/schema.py
  user/sqlfiles/create.sql
Labels: access control

#397 Issue 4 Streaming
  ui/dashboard/public/icons/refresh.svg
  ui/dashboard/src/assets/loading.svg
  ui/dashboard/src/assets/obs-instruction/2.png
  ui/dashboard/src/components/RTMPStream.vue
  ui/dashboard/src/components/form/MediaType.vue
  ui/dashboard/src/components/objects/Moveable.vue
  ui/dashboard/src/components/objects/Streamer/composable.js
  ui/dashboard/src/components/objects/Streamer/index.vue
  ui/dashboard/src/components/stage/SettingPopup/index.vue
  ui/dashboard/src/components/stage/SettingPopup/settings/CreateStream.vue
  ui/dashboard/src/components/stage/Toolbox/tools/Backdrop.vue
  ui/dashboard/src/components/stage/Toolbox/tools/Stream/index.vue
  ui/dashboard/src/services/graphql/stage.js
  ui/dashboard/src/services/rest/nms.js
  ui/dashboard/src/store/modules/stage/index.js
  ui/dashboard/src/views/backstage/Media/MediaForm.vue
  ui/dashboard/src/views/backstage/Media/OBSInstruction.vue
Labels: streaming

#398 Issue 337 Voice and Emoji
  ui/dashboard/src/services/speech/index.js
Labels: streaming

#405 Issue 30 Audio Tool
  ui/dashboard/src/components/form/ImagePicker.vue
  ui/dashboard/src/components/stage/AudioPlayer.vue
  ui/dashboard/src/components/stage/Chat/Reaction.vue
  ui/dashboard/src/components/stage/Toolbox/tools/Audio.vue
  ui/dashboard/src/store/modules/stage/index.js
Labels: audio

#411 Vanity URLs
  system/dev/dev_app1_nginx_upstage.conf
  system/prod/app1_nginx_upstage.conf
Labels: access control

#412 Issue 29 Player and Audience counter
  event_archive/actions.py
  ui/dashboard/src/components/stage/PlayerAudienceCounter.vue
  ui/dashboard/src/components/stage/StageTable.vue
  ui/dashboard/src/components/stage/composable.js
  ui/dashboard/src/services/mqtt/index.js
  ui/dashboard/src/store/modules/stage/index.js
  ui/dashboard/src/utils/constants.js
  ui/dashboard/src/views/Home.vue
  ui/dashboard/src/views/backstage/Stages.vue
  ui/dashboard/src/views/live/ConnectionStatus.vue
Labels: stage

#415 Remove User Manual
  docs/backstage-list.png
  docs/backstage-stage-creation.png
  docs/change-profile02.png
  docs/change_password.png
  docs/index.rst
  docs/login-01.png
  docs/register_box2.png
  docs/stage_details.png
  docs/user_manual.rst
Labels: documentation

#423 Issue 418 Auto detect live streams option
  ui/dashboard/src/components/stage/Toolbox/tools/Stream/index.vue
  ui/dashboard/src/router/index.js
  ui/dashboard/src/store/modules/stage/index.js
  ui/dashboard/src/store/modules/stage/reusable.js
  ui/dashboard/src/views/backstage/StageManagement/Customization.vue
  ui/dashboard/src/views/backstage/StageManagement/index.vue
Labels: streaming

#429 Prevent nginx from caching logical resources
  system/dev/dev_app1_nginx_upstage.conf
  system/prod/app1_nginx_upstage.conf
Labels: access control

#430 Issue 428 Custom scrollbar
  ui/dashboard/src/styles/custom.scss
Labels: stage

#436 Issue 427 Resizing frame & save button
  ui/dashboard/public/icons/loop.svg
  ui/dashboard/public/icons/toggle_off.svg
  ui/dashboard/public/icons/toggle_on.svg
  ui/dashboard/src/components/Icon.vue
  ui/dashboard/src/components/form/Switch.vue
  ui/dashboard/src/components/objects/Moveable.vue
  ui/dashboard/src/components/stage/Board.vue
  ui/dashboard/src/components/stage/Toolbox/tools/Audio.vue
  ui/dashboard/src/store/modules/stage/index.js
  ui/dashboard/src/styles/speech.scss
  ui/dashboard/src/views/backstage/StageManagement/General.vue
  ui/dashboard/src/views/backstage/StageManagement/SweepStage.vue
Labels: stage

#439 Issue 377 Finding players
  config/schema.py
  config/settings/__init__.py
  ui/dashboard/src/components/MultiTransferColumn.vue
  ui/dashboard/src/views/backstage/StageManagement/General.vue
Labels: access control

#442 Issue 245 Chat Management
  ui/dashboard/src/components/Tabs.vue
  ui/dashboard/src/views/backstage/StageManagement/Chat.vue
  ui/dashboard/src/views/backstage/StageManagement/ClearChat.vue
  ui/dashboard/src/views/backstage/StageManagement/General.vue
  ui/dashboard/src/views/backstage/StageManagement/SweepStage.vue
  ui/dashboard/src/views/backstage/StageManagement/index.vue
Labels: chat
