Repository upstage-org/upstage, pull requests merged in 2021-02, with the labels that each got.

#135 Basic Video Streaming
  ui/dashboard/public/demo/streams/bunny.mp4
  ui/dashboard/public/demo/streams/bunny.png
  ui/dashboard/src/assets/dog.png
  ui/dashboard/src/components/form/InputButtonPostfix.vue
  ui/dashboard/src/components/objects/Avatar.vue
  ui/dashboard/src/components/objects/Avatar/ContextMenu.vue
  ui/dashboard/src/components/objects/Avatar/index.vue
  ui/dashboard/src/components/objects/Object.vue
  ui/dashboard/src/components/objects/Skeleton.vue
  ui/dashboard/src/components/objects/Streamer/composable.js
  ui/dashboard/src/components/objects/Streamer/index.vue
  ui/dashboard/src/components/stage/Board.vue
  ui/dashboard/src/components/stage/Chat.vue
  ui/dashboard/src/components/stage/SettingPopup/index.vue
  ui/dashboard/src/components/stage/SettingPopup/settings/Chat.vue
  ui/dashboard/src/components/stage/SettingPopup/settings/CreateStream.vue
  ui/dashboard/src/components/stage/Toolbox/TopBar.vue
  ui/dashboard/src/components/stage/Toolbox/index.vue
  ui/dashboard/src/components/stage/Toolbox/tools/Draw/composable.js
  ui/dashboard/src/components/stage/Toolbox/tools/Stream.vue
  ui/dashboard/src/services/mqtt.js
  ui/dashboard/src/store/modules/stage/demoData.js
  ui/dashboard/src/store/modules/stage/index.js
  ui/dashboard/src/store/modules/stage/reusable.js
  ui/dashboard/src/utils/canvas.js
  ui/dashboard/src/utils/constants.js
Labels: streaming

#136 Speech Bubbles
  ui/dashboard/src/components/objects/Object.vue
  ui/dashboard/src/components/objects/Topping.vue
Labels: avatars, stage

#140 User mutation in schema
  user/schema.py
Labels: access control

#143 Issue 137 cleanup gql 3
  auth/auth_api.py
  user/schema.py
  utils/graphql_utils.py
Labels: access control

#145 Issue 64 text tool
  ui/dashboard/package.json
  ui/dashboard/src/components/form/ColorPicker.vue
  ui/dashboard/src/components/form/Dropdown.vue
  ui/dashboard/src/components/objects/Object.vue
  ui/dashboard/src/components/stage/Toolbox/TopBar.vue
  ui/dashboard/src/components/stage/Toolbox/index.vue
  ui/dashboard/src/components/stage/Toolbox/tools/Draw/index.vue
  ui/dashboard/src/components/stage/Toolbox/tools/Text.vue
  ui/dashboard/src/store/modules/stage/index.js
  ui/dashboard/src/store/modules/stage/reusable.js
  ui/dashboard/src/styles/custom.scss
  ui/dashboard/src/views/live/Live.vue
  ui/dashboard/yarn.lock
Labels: chat

#152 Reduce box shadows
  ui/dashboard/src/components/NavBar.vue
  ui/dashboard/src/components/objects/Avatar/ContextMenu.vue
  ui/dashboard/src/styles/custom.scss
  ui/dashboard/src/styles/mixins.scss
  ui/dashboard/src/views/Home.vue
  ui/dashboard/src/views/dashboard/Layout.vue
Labels: stage

#154 GraphQL Authentication
  ui/dashboard/src/components/LoginForm.vue
  ui/dashboard/src/components/NavBar.vue
  ui/dashboard/src/components/form/Field.vue
  ui/dashboard/src/router/index.js
  ui/dashboard/src/services/graphql/composable.js
  ui/dashboard/src/services/graphql/graphql.js
  ui/dashboard/src/services/graphql/user.js
  ui/dashboard/src/store/modules/auth.js
  ui/dashboard/src/styles/custom.scss
  ui/dashboard/src/views/Home.vue
  ui/dashboard/src/views/Login.vue
  ui/dashboard/src/views/Register.vue
Labels: access control

#156 Issue 137 cleanup gql 8
  user/schema.py
  user/user_utils.py
  utils/graphene_utils.py
  utils/graphql_utils.py
Labels: access control
